name: Workflow for Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-on-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies and PulseAudio
          run: |
            sudo chown -R $USER:$USER /var/cache/apt/archives/

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache APT packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives/
          key: ${{ runner.os }}-apt-${{ steps.date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install dependencies and PulseAudio
        run: |
          sudo apt-get update
          sudo apt-get install -y pulseaudio ffmpeg portaudio19-dev
          sudo chown -R $USER:$USER /var/cache/apt/archives/
          pulseaudio --start
          pactl load-module module-null-sink sink_name=virtual_speaker
          pactl set-default-sink virtual_speaker
          pip install -r requirements.txt
          pip install coverage

      - name: Modify user permissions and check audio
        run: |
          sudo usermod -aG audio $USER
          sudo chmod 666 /run/user/1001/pulse/native
          pulseaudio --check
          pactl info

      - name: Configure ALSA to use PulseAudio
        run: |
          echo 'pcm.!default { type pulse }' >> ~/.asoundrc
          echo 'ctl.!default { type pulse }' >> ~/.asoundrc

      - name: Test simplified PulseAudio setup
        run: |
          pulseaudio --kill
          pulseaudio --start --log-target=syslog
          pactl load-module module-null-sink
          pactl set-default-sink null
          pactl info

      - name: Generate coverage report
        env:
          PULSE_SERVER: unix:/run/user/1001/pulse/native
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_API_VERSION: ${{ secrets.AZURE_API_VERSION }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
          AZURE_SPEECH_KEY: ${{ secrets.AZURE_SPEECH_KEY }}
          AZURE_SPEECH_REGION: ${{ secrets.AZURE_SPEECH_REGION }}
          VOICE_NAME: ${{ secrets.VOICE_NAME }}
        run: |
          coverage run app.py

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.4.1
        with:
          flags: smart-tests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
