name: Workflow for Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies and PulseAudio
        run: |
          sudo apt-get update
          sudo apt-get install -y pulseaudio
          echo "default-sample-rate = 48000" >> /etc/pulse/daemon.conf
          echo "load-module module-virtual-source source_name=vsource" | tee -a /etc/pulse/default.pa
          echo "set-default-source vsource" | tee -a /etc/pulse/default.pa
          pulseaudio --start
          pactl info
          pip install -r requirements.txt
          pip install coverage

      - name: Check PulseAudio
        run: |
          pactl info

      - name: Generate coverage report
        env:
          PULSE_SERVER: 127.0.0.1
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_API_VERSION: ${{ secrets.AZURE_API_VERSION }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
          AZURE_SPEECH_KEY: ${{ secrets.AZURE_SPEECH_KEY }}
          AZURE_SPEECH_REGION: ${{ secrets.AZURE_SPEECH_REGION }}
          VOICE_NAME: ${{ secrets.VOICE_NAME }}
        run: |
          coverage run app.py

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.4.1
        with:
          flags: smart-tests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
