name: SonarCloud-test
on:
  push:
    branches:
      - main
      - dev-main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set permission for apt cache dir
        run: |
              sudo chown -R $USER:$USER /var/cache/apt/
  
  
      - name: Get current date
        id: date
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_ENV
  
      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
  
      - name: Cache APT packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives/
          key: ${{ runner.os }}-apt-${{ env.date }}
          restore-keys: |
            ${{ runner.os }}-apt-
  
      - name: Install dependencies and PulseAudio
        run: |
          sudo apt-get update
          sudo apt-get install -y pulseaudio ffmpeg portaudio19-dev
          sudo chown -R $USER:$USER /var/cache/apt/archives/
          pulseaudio --start
          pactl load-module module-null-sink sink_name=virtual_speaker
          pactl set-default-sink virtual_speaker
          pip install -r requirements.txt
          pip install coverage
  
      - name: Modify user permissions and check audio
        run: |
          sudo usermod -aG audio $USER
          sudo chmod -R 666 /run/user/
          sudo pulseaudio --check
          sudo pactl info
  
      - name: Configure ALSA to use PulseAudio
        run: |
          echo 'pcm.!default { type pulse }' >> ~/.asoundrc
          echo 'ctl.!default { type pulse }' >> ~/.asoundrc
  
      - name: Test simplified PulseAudio setup
        run: |
          pulseaudio --kill
          pulseaudio --start --log-target=syslog
          pactl load-module module-null-sink
          pactl set-default-sink null
          pactl info

      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        env:
          PULSE_SERVER: unix:/run/user/1001/pulse/native
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_API_VERSION: ${{ secrets.AZURE_API_VERSION }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
          AZURE_SPEECH_KEY: ${{ secrets.AZURE_SPEECH_KEY }}
          AZURE_SPEECH_REGION: ${{ secrets.AZURE_SPEECH_REGION }}
          VOICE_NAME: ${{ secrets.VOICE_NAME }}
          WHISPER_MODEL_NAME: ${{ secrets.WHISPER_MODEL_NAME }}
          TTS_MODEL_NAME: ${{ secrets.TTS_MODEL_NAME }}
          TTS_VOICE_NAME: ${{ secrets.TTS_VOICE_NAME }}
        run: tox -e py312
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}